using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using LobbyClient;
using PlasmaShared;
using Ratings;
using ZeroKWeb;

namespace ZkLobbyServer.Api
{
    /// <summary>
    /// <see cref="ILobbyServerApi"/> against a lobby server in another process. The twin of
    /// <see cref="InProcessLobbyServerApi"/>; the website holds one or the other and cannot tell
    /// which from the call sites.
    ///
    /// **The members are written out rather than generated by a proxy.** Forty one-line forwards
    /// is more typing than a DispatchProxy, and it is what the reader of a privileged client wants:
    /// every call is greppable, and there is no reflection deciding at runtime what to send. The
    /// risk of hand-writing them - forgetting one - is not a risk, because C# will not let this
    /// class exist with a member missing, and a test asserts every interface member is reachable
    /// over the wire besides.
    ///
    /// **Blocking calls go through Task.Run on purpose.** Fourteen members are synchronous and
    /// this is HTTP, so something has to wait. On .NET Framework, waiting on a task that captured
    /// an ASP.NET request context deadlocks; starting it on the pool first is the standard way out.
    /// When the website is on .NET 9 with no synchronization context the extra hop is harmless, and
    /// the right fix is making those members async, which is a change to the interface and its call
    /// sites rather than to this file.
    /// </summary>
    public class RemoteLobbyServerApi : ILobbyServerApi, IDisposable
    {
        private readonly HttpClient client;
        private readonly string baseUrl;

        public RemoteLobbyServerApi(string baseUrl, string secret, HttpMessageHandler handler = null,
                                    bool allowInsecureTransport = false)
        {
            if (string.IsNullOrWhiteSpace(baseUrl))
                throw new ArgumentException("the lobby API needs somewhere to call", nameof(baseUrl));
            // Same refusal as the host's, so neither end can be brought up unauthenticated.
            if (string.IsNullOrWhiteSpace(secret))
                throw new ArgumentException("the lobby API client needs the shared secret", nameof(secret));

            LobbyApiProtocol.RequireTrustworthyTransport(baseUrl, allowInsecureTransport);
            this.baseUrl = baseUrl.TrimEnd('/');
            client = handler == null ? new HttpClient() : new HttpClient(handler);
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue(LobbyApiProtocol.AuthorizationScheme, secret);
        }

        // ---- the wire ---------------------------------------------------------------------

        private async Task<T> CallAsync<T>(string member, object arguments)
        {
            var url = baseUrl + LobbyApiProtocol.PathPrefix + member;
            var body = new StringContent(LobbyApiProtocol.Serialize(arguments ?? new object()),
                                         Encoding.UTF8, "application/json");

            var response = await client.PostAsync(url, body).ConfigureAwait(false);
            var text = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            var parsed = string.IsNullOrWhiteSpace(text)
                ? null
                : LobbyApiProtocol.Deserialize<Newtonsoft.Json.Linq.JObject>(text);

            if (!response.IsSuccessStatusCode)
                throw new LobbyApiException(member, (int)response.StatusCode,
                    parsed?["error"]?.ToString() ?? response.ReasonPhrase);

            var result = parsed?["result"];
            return result == null || result.Type == Newtonsoft.Json.Linq.JTokenType.Null
                ? default(T)
                : result.ToObject<T>();
        }

        private Task CallAsync(string member, object arguments) => CallAsync<object>(member, arguments);

        /// <summary>See the class note on why this is not a plain GetAwaiter().GetResult().</summary>
        private T Call<T>(string member, object arguments) =>
            Task.Run(() => CallAsync<T>(member, arguments)).GetAwaiter().GetResult();

        private void CallVoid(string member, object arguments) => Call<object>(member, arguments);

        // ---- commands ---------------------------------------------------------------------

        public Task GhostChanSay(string channelName, string text, bool isEmote = true, bool isRing = false)
            => CallAsync("GhostChanSay", new { channelName, text, isEmote, isRing });

        public Task GhostPm(string name, string text) => CallAsync("GhostPm", new { name, text });

        public Task GhostSay(Say say, int? battleID = null) => CallAsync("GhostSay", new { say, battleID });

        public Task KickFromServer(string kickerName, string kickeeName, string reason)
            => CallAsync("KickFromServer", new { kickerName, kickeeName, reason });

        public Task ForceJoinBattle(string playerName, string battleHost)
            => CallAsync("ForceJoinBattle", new { playerName, battleHost });

        public Task SetTopic(string channel, string topic, string author)
            => CallAsync("SetTopic", new { channel, topic, author });

        public Task RequestJoinPlanet(string name, int planetId, string attackerFaction)
            => CallAsync("RequestJoinPlanet", new { name, planetId, attackerFaction });

        public Task SendSiteToLobbyCommand(string user, SiteToLobbyCommand command)
            => CallAsync("SendSiteToLobbyCommand", new { user, command });

        public Task SetEngine(string engine) => CallAsync("SetEngine", new { engine });

        public Task SetGame(string game) => CallAsync("SetGame", new { game });

        public Task OnServerMapsChanged() => CallAsync("OnServerMapsChanged", null);

        public Task PublishAccountUpdate(int accountID) => CallAsync("PublishAccountUpdate", new { accountID });

        public Task PublishUserProfileUpdate(int accountID)
            => CallAsync("PublishUserProfileUpdate", new { accountID });

        public Task ReportUser(int reporterAccountID, int reportedAccountID, string report)
            => CallAsync("ReportUser", new { reporterAccountID, reportedAccountID, report });

        // ---- queries ----------------------------------------------------------------------

        public bool IsLobbyConnected(string user) => Call<bool>("IsLobbyConnected", new { user });

        public int GetDiscordUserCount() => Call<int>("GetDiscordUserCount", null);

        public int ConnectedUserCount => Call<int>("ConnectedUserCount", null);

        public NewsList GetCurrentNewsList() => Call<NewsList>("GetCurrentNewsList", null);

        public LadderList GetCurrentLadderList() => Call<LadderList>("GetCurrentLadderList", null);

        public ForumList GetCurrentForumList(int? accountID)
            => Call<ForumList>("GetCurrentForumList", new { accountID });

        public void OnNewsChanged() => CallVoid("OnNewsChanged", null);

        // ---- channels ---------------------------------------------------------------------

        public void AddClanChannel(int clanID) => CallVoid("AddClanChannel", new { clanID });

        public bool CanJoinChannel(int accountID, string channel)
            => Call<bool>("CanJoinChannel", new { accountID, channel });

        // ---- login throttling --------------------------------------------------------------

        public bool VerifyIp(string ip) => Call<bool>("VerifyIp", new { ip });

        public void LogIpFailure(string ip) => CallVoid("LogIpFailure", new { ip });

        // ---- planetwars ---------------------------------------------------------------------

        public bool IsPlanetWarsMatchMakerRunning => Call<bool>("IsPlanetWarsMatchMakerRunning", null);

        public PwPhase? PlanetWarsPhase => Call<PwPhase?>("PlanetWarsPhase", null);

        public void AddPlanetWarsAttackOption(int planetID, int attackerFactionId)
            => CallVoid("AddPlanetWarsAttackOption", new { planetID, attackerFactionId });

        public List<PlanetBattleInfo> GetPlanetBattles(string mapName)
            => Call<List<PlanetBattleInfo>>("GetPlanetBattles", new { mapName });

        public List<PlanetBattleInfo> GetPlanetWarsBattles()
            => Call<List<PlanetBattleInfo>>("GetPlanetWarsBattles", null);

        public PwMatchCommand GeneratePlanetWarsLobbyCommand(string playerName, string playerFaction)
            => Call<PwMatchCommand>("GeneratePlanetWarsLobbyCommand", new { playerName, playerFaction });

        // ---- ratings ----------------------------------------------------------------------------

        public void ForceRatingsUpdate() => CallVoid("ForceRatingsUpdate", null);

        public void ResetPlanetwarsRatings() => CallVoid("ResetPlanetwarsRatings", null);

        public Dictionary<DateTime, float> GetPlayerRatingHistory(RatingCategory category, int accountID)
            => Call<Dictionary<DateTime, float>>("GetPlayerRatingHistory", new { category, accountID })
               ?? new Dictionary<DateTime, float>();

        public InternalRatingInfo GetInternalRating(RatingCategory category, int accountID, DateTime time)
            => Call<InternalRatingInfo>("GetInternalRating", new { category, accountID, time });

        public List<MapRatingInfo> GetMapRanking(Ratings.MapRatings.Category category)
            => Call<List<MapRatingInfo>>("GetMapRanking", new { category })
               ?? new List<MapRatingInfo>();

        // ---- battles --------------------------------------------------------------------------

        public LobbyBattleStats GetBattleStats() => Call<LobbyBattleStats>("GetBattleStats", null);

        public bool IsUserInAnyBattle(string userName) => Call<bool>("IsUserInAnyBattle", new { userName });

        public Task ConnectPlayerToBattle(string userName, int battleID)
            => CallAsync("ConnectPlayerToBattle", new { userName, battleID });

        // ---- tournaments -----------------------------------------------------------------------

        public List<TourneyBattleInfo> GetTourneyBattles()
            => Call<List<TourneyBattleInfo>>("GetTourneyBattles", null);

        public TourneyBattleInfo GetTourneyBattle(int battleID)
            => Call<TourneyBattleInfo>("GetTourneyBattle", new { battleID });

        public Task<int> CreateTourneyBattle(TourneyPrototypeInfo prototype)
            => CallAsync<int>("CreateTourneyBattle", new { prototype });

        public Task<bool> RemoveTourneyBattle(int battleID)
            => CallAsync<bool>("RemoveTourneyBattle", new { battleID });

        public Task ForceJoinTourneyBattle(string player, int battleID)
            => CallAsync("ForceJoinTourneyBattle", new { player, battleID });

        // ---- single sign-on ---------------------------------------------------------------------

        public int? RedeemSessionToken(string token) => Call<int?>("RedeemSessionToken", new { token });

        public void Dispose() => client.Dispose();
    }

    /// <summary>A call that reached the server and was refused, or did not reach it at all.</summary>
    public class LobbyApiException : Exception
    {
        public LobbyApiException(string member, int status, string error)
            : base("lobby API " + member + " failed (" + status + "): " + error)
        {
            Member = member;
            Status = status;
        }

        public string Member { get; }
        public int Status { get; }
    }
}
