#!/usr/bin/env python3
"""
Generates ZkData.Core/ZkDataContext.ColumnFacets.cs from db/schema/schema.txt.

The facets EF Core would otherwise choose differently from the database that already
exists: non-Unicode columns and default constraints. Both are read out of the snapshot
rather than inferred, because the snapshot is what the database actually is - EF6's
configuration says IsUnicode(false) in only 19 places, while the schema has many more,
the rest having arrived through 117 migrations.

    ./ZkData.Core/generate-column-facets.py
"""
import re, pathlib, sys

SCHEMA = pathlib.Path("db/schema/schema.txt")
TARGET = pathlib.Path("ZkData.Core/ZkDataContext.ColumnFacets.cs")

# Tables the EF Core model does not have, or whose names differ - skipping them keeps the
# generated file compiling while those are dealt with separately.
SKIP_TABLES = {"__MigrationHistory",
               "EventAccount", "EventClan", "EventFaction", "EventPlanet", "EventSpringBattle"}


def indexes():
    """Non-unique, non-primary indexes, as (table, [columns])."""
    table = None
    for line in SCHEMA.read_text(encoding="utf-8").splitlines():
        if line.startswith("TABLE "):
            table = line[6:].strip()
            continue
        if not table or table in SKIP_TABLES:
            continue
        m = re.match(r'  INDEX \(([^)]*)\)\s*$', line)
        if m and m.group(1).strip():
            yield table, [c.strip() for c in m.group(1).split(",")]


def parse():
    table = None
    for line in SCHEMA.read_text(encoding="utf-8").splitlines():
        if line.startswith("TABLE "):
            table = line[6:].strip()
            continue
        if not line.startswith("  ") or not table:
            continue
        if line.strip().startswith(("PRIMARY KEY", "INDEX", "UNIQUE INDEX", "FOREIGN KEY")):
            continue
        m = re.match(r'  (\S+)\s+(\S+)\s+(NOT NULL|NULL)(.*)$', line)
        if not m:
            continue
        column, ctype, _, rest = m.groups()
        yield table, column, ctype, rest.strip()


def main():
    unicode_off, defaults = [], []
    for table, column, ctype, rest in parse():
        if table in SKIP_TABLES:
            continue
        base = ctype.split("(")[0]
        if base in ("varchar", "char"):
            unicode_off.append((table, column))
        m = re.search(r'DEFAULT \((.*)\)$', rest)
        if m:
            defaults.append((table, column, m.group(1)))

    lines = ['''// GENERATED by ZkData.Core/generate-column-facets.py - do not edit by hand.
//
// Column facets taken from db/schema/schema.txt, which is what the database actually is.
// EF Core would otherwise pick its own: nvarchar for every string, and no default
// constraints at all. Neither is wrong in the abstract; both are wrong against a database
// that already exists.
//
// EF6's own configuration declares IsUnicode(false) in 19 places. The schema has many
// more, the rest having arrived through 117 migrations - which is why this is read from
// the schema rather than translated from the fluent configuration.
using Microsoft.EntityFrameworkCore;

namespace ZkData
{
    public partial class ZkDataContext
    {
        partial void ConfigureColumnFacets(ModelBuilder modelBuilder)
        {''']

    lines.append("            // non-Unicode columns (%d)" % len(unicode_off))
    for table, column in unicode_off:
        lines.append('            Facet(modelBuilder, "%s", "%s", p => p.IsUnicode(false));' % (table, column))

    lines.append("")
    lines.append("            // default constraints (%d)" % len(defaults))
    for table, column, expression in defaults:
        lines.append('            Facet(modelBuilder, "%s", "%s", p => p.HasDefaultValueSql("%s"));'
                     % (table, column, expression.replace('"', '\\"')))

    index_list = list(indexes())
    lines.append("")
    lines.append("            // indexes the database has that EF Core would not create (%d)." % len(index_list))
    lines.append("            // EF6 indexed foreign key columns even when they were already the leading")
    lines.append("            // columns of the primary key; EF Core treats those as redundant and skips")
    lines.append("            // them. Declaring them keeps the schema identical.")
    for table, columns in index_list:
        lines.append('            Index(modelBuilder, "%s", new[] { %s });'
                     % (table, ", ".join('"%s"' % c.split()[0] for c in columns)))

    lines.append('''        }

        /// <summary>
        /// Applies a facet by table and column name, skipping quietly if the model has no
        /// such property. Names are the database's, which is what the snapshot records;
        /// where a model property does not match, that is a difference the schema diff
        /// will report rather than something to crash on here.
        /// </summary>
        /// <summary>Declares an index by table and column names, skipping if the model lacks them.</summary>
        private static void Index(ModelBuilder modelBuilder, string table, string[] columns)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                foreach (var column in columns)
                    if (entity.FindProperty(column) == null) return;
                modelBuilder.Entity(entity.ClrType).HasIndex(columns);
                return;
            }
        }

        private static void Facet(ModelBuilder modelBuilder, string table, string column,
            System.Action<Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder> configure)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                var property = entity.FindProperty(column);
                if (property == null) continue;
                configure(modelBuilder.Entity(entity.ClrType).Property(column));
                return;
            }
        }
    }
}''')

    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %d IsUnicode(false) and %d default constraints" % (len(unicode_off), len(defaults)))


if __name__ == "__main__":
    main()
