#!/usr/bin/env python3
"""
Generates ZkData.Core/ZkDataContext.ColumnFacets.cs from db/schema/schema.txt.

The facets EF Core would otherwise choose differently from the database that already
exists: non-Unicode columns and default constraints. Both are read out of the snapshot
rather than inferred, because the snapshot is what the database actually is - EF6's
configuration says IsUnicode(false) in only 19 places, while the schema has many more,
the rest having arrived through 117 migrations.

    ./ZkData.Core/generate-column-facets.py
"""
import re, pathlib, sys

SCHEMA = pathlib.Path("db/schema/schema.txt")
TARGET = pathlib.Path("ZkData.Core/ZkDataContext.ColumnFacets.cs")

# Tables the EF Core model does not have, or whose names differ - skipping them keeps the
# generated file compiling while those are dealt with separately.
SKIP_TABLES = {"__MigrationHistory"}


def indexes():
    """Non-unique, non-primary indexes, as (table, [columns])."""
    table = None
    for line in SCHEMA.read_text(encoding="utf-8").splitlines():
        if line.startswith("TABLE "):
            table = line[6:].strip()
            continue
        if not table or table in SKIP_TABLES:
            continue
        m = re.match(r'  (UNIQUE )?INDEX \(([^)]*)\)(?: WHERE (.*?))?(?:  \[.*\])?\s*$', line)
        if m and m.group(2).strip():
            yield (table, [c.strip() for c in m.group(2).split(",")],
                   bool(m.group(1)), m.group(3))


def foreign_keys():
    """(table, [columns], cascade?) for every foreign key in the snapshot."""
    table = None
    for line in SCHEMA.read_text(encoding="utf-8").splitlines():
        if line.startswith("TABLE "):
            table = line[6:].strip()
            continue
        if not table or table in SKIP_TABLES:
            continue
        m = re.match(r'  FOREIGN KEY \(([^)]*)\) -> (\S+)(.*)$', line)
        if m:
            columns = [c.strip() for c in m.group(1).split(",")]
            yield table, columns, "ON DELETE CASCADE" in m.group(3)


def parse():
    table = None
    for line in SCHEMA.read_text(encoding="utf-8").splitlines():
        if line.startswith("TABLE "):
            table = line[6:].strip()
            continue
        if not line.startswith("  ") or not table:
            continue
        if line.strip().startswith(("PRIMARY KEY", "INDEX", "UNIQUE INDEX", "FOREIGN KEY")):
            continue
        m = re.match(r'  (\S+)\s+(\S+)\s+(NOT NULL|NULL)(.*)$', line)
        if not m:
            continue
        column, ctype, _, rest = m.groups()
        yield table, column, ctype, rest.strip()


def main():
    unicode_off, defaults, lengths = [], [], []
    for table, column, ctype, rest in parse():
        if table in SKIP_TABLES:
            continue
        base = ctype.split("(")[0]
        if base in ("varchar", "char"):
            unicode_off.append((table, column))
        m_len = re.match(r'n?(?:var)?char\((\d+|max)\)$', ctype)
        if m_len:
            lengths.append((table, column, m_len.group(1), base))
        m = re.search(r'DEFAULT \((.*)\)$', rest)
        if m:
            defaults.append((table, column, m.group(1)))

    lines = ['''// GENERATED by ZkData.Core/generate-column-facets.py - do not edit by hand.
//
// Column facets taken from db/schema/schema.txt, which is what the database actually is.
// EF Core would otherwise pick its own: nvarchar for every string, and no default
// constraints at all. Neither is wrong in the abstract; both are wrong against a database
// that already exists.
//
// EF6's own configuration declares IsUnicode(false) in 19 places. The schema has many
// more, the rest having arrived through 117 migrations - which is why this is read from
// the schema rather than translated from the fluent configuration.
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ZkData
{
    public partial class ZkDataContext
    {
        partial void ConfigureColumnFacets(ModelBuilder modelBuilder)
        {''']

    lines.append("            // non-Unicode columns (%d)" % len(unicode_off))
    for table, column in unicode_off:
        lines.append('            Facet(modelBuilder, "%s", "%s", p => p.IsUnicode(false));' % (table, column))

    lines.append("")
    lines.append("            // string lengths, from the schema (%d). Some disagree with the" % len(lengths))
    lines.append("            // entity attributes - migrations widened columns without updating them.")
    for table, column, length, ctype in lengths:
        if length == "max":
            # the column type carries whether it is unicode; nvarchar(max) for a
            # varchar(max) column would silently double its storage and change collation
            setter = 'p.HasColumnType("%s(max)")' % ("nvarchar" if ctype.startswith("n") else "varchar")
        else:
            setter = "p.HasMaxLength(%s)" % length
        lines.append('            Facet(modelBuilder, "%s", "%s", p => %s);' % (table, column, setter))

    lines.append("")
    lines.append("            // default constraints (%d)" % len(defaults))
    for table, column, expression in defaults:
        lines.append('            Facet(modelBuilder, "%s", "%s", p => p.HasDefaultValueSql("%s"));'
                     % (table, column, expression.replace('"', '\\"')))

    index_list = list(indexes())
    lines.append("")
    lines.append("            // indexes the database has that EF Core would not create (%d)." % len(index_list))
    lines.append("            // EF6 indexed foreign key columns even when they were already the leading")
    lines.append("            // columns of the primary key; EF Core treats those as redundant and skips")
    lines.append("            // them. Declaring them keeps the schema identical.")
    for table, columns, unique, filter_expression in index_list:
        lines.append('            Index(modelBuilder, "%s", new[] { %s }, %s, %s);'
                     % (table, ", ".join('"%s"' % c.split()[0] for c in columns),
                        "true" if unique else "false",
                        'null' if not filter_expression else '"%s"' % filter_expression.replace('"', '\\"')))

    fks = list(foreign_keys())
    cascading = sum(1 for _, _, c in fks if c)
    lines.append("")
    lines.append("            // delete behaviour for all %d foreign keys, %d of them cascading." % (len(fks), cascading))
    lines.append("            // Taken from the schema rather than from EF6's configuration: the")
    lines.append("            // configuration says nothing for many of them, and inferring EF6's default")
    lines.append("            // produces cascade paths SQL Server rejects outright. The database cannot")
    lines.append("            // contain a cycle, because it exists.")
    for table, columns, cascade in fks:
        lines.append('            Fk(modelBuilder, "%s", new[] { %s }, DeleteBehavior.%s);'
                     % (table, ", ".join('"%s"' % c for c in columns), "Cascade" if cascade else "Restrict"))

    lines.append('''        }

        /// <summary>
        /// Applies a facet by table and column name, skipping quietly if the model has no
        /// such property. Names are the database's, which is what the snapshot records;
        /// where a model property does not match, that is a difference the schema diff
        /// will report rather than something to crash on here.
        /// </summary>
        /// <summary>
        /// Sets a foreign key's delete behaviour, matched by the columns it is on. Skips
        /// quietly when the model has no such relationship - that is a difference the
        /// schema diff reports, not something to crash on here.
        /// </summary>
        private static void Fk(ModelBuilder modelBuilder, string table, string[] columns, DeleteBehavior behavior)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                foreach (var foreignKey in entity.GetForeignKeys())
                {
                    var names = foreignKey.Properties.Select(p => p.Name).ToArray();
                    if (names.Length != columns.Length) continue;
                    if (names.Except(columns).Any()) continue;
                    foreignKey.DeleteBehavior = behavior;
                    return;
                }
            }
        }

        /// <summary>Declares an index by table and column names, skipping if the model lacks them.</summary>
        private static void Index(ModelBuilder modelBuilder, string table, string[] columns, bool unique, string filter)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                // join tables are shared-type entities over Dictionary<string, object>;
                // modelBuilder.Entity() cannot take them
                if (entity.HasSharedClrType) continue;
                foreach (var column in columns)
                    if (entity.FindProperty(column) == null) return;
                var index = modelBuilder.Entity(entity.ClrType).HasIndex(columns);
                if (unique) index.IsUnique();

                // EF Core adds "WHERE [col] IS NOT NULL" to a unique index over a nullable
                // column. Sometimes the database agrees and sometimes it does not - SteamID
                // is filtered, Text and ShortName are not - so the filter is taken from the
                // schema per index rather than applied or removed by rule. A first attempt
                // removed them all and broke the one that was right.
                index.HasFilter(filter);
                return;
            }
        }

        private static void Facet(ModelBuilder modelBuilder, string table, string column,
            System.Action<Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder> configure)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                // join tables are shared-type entities over Dictionary<string, object>;
                // modelBuilder.Entity() cannot take them
                if (entity.HasSharedClrType) continue;
                var property = entity.FindProperty(column);
                if (property == null) continue;
                configure(modelBuilder.Entity(entity.ClrType).Property(column));
                return;
            }
        }
    }
}''')

    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %d IsUnicode(false) and %d default constraints" % (len(unicode_off), len(defaults)))


if __name__ == "__main__":
    main()
