using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using ZkLobbyServer;

namespace ZkData.Core
{
    /// <summary>
    /// Phase 1's question, made executable: **can every member of <see cref="ILobbyServerApi"/>
    /// actually cross a process boundary?**
    ///
    /// There is already one check on that seam, and it is a good one - the port projects compile
    /// this interface with no reference to ZkLobbyServer, so a member naming a server-side type
    /// breaks the build. But it only catches types that live in the SERVER. It says nothing about
    /// an <c>Account</c>, which compiles perfectly well on both sides and is an EF entity attached
    /// to the caller's DbContext: passing one works because the two halves share a process, which
    /// is the exact thing Phase 1 is trying to end.
    ///
    /// **The hand-written list was wrong, which is why this exists.** HOSTING.md named two members
    /// as the remaining work, ReportUser and AddPlanetWarsAttackOption. There are six. The other
    /// four - PublishAccountUpdate, PublishUserProfileUpdate, AddClanChannel and CanJoinChannel -
    /// pass entities just as plainly and had simply not been counted. Every hand-written list in
    /// this port has turned out incomplete; this one is derived.
    ///
    /// The walk is TRANSITIVE, which is the part a reader cannot do reliably. A DTO whose own
    /// shape is fine but which holds an entity two levels down is not crossable either, and
    /// nothing about its signature says so.
    ///
    /// What counts as crossable: primitives, string, decimal, DateTime, TimeSpan, Guid, enums,
    /// and any type whose public fields and properties are themselves crossable. What does not:
    /// <see cref="ZkDataContext"/>, and any type it exposes a DbSet for - the entity set is read
    /// off the model rather than listed here, so adding an entity cannot quietly widen it.
    /// </summary>
    public static class SeamVerification
    {
        private const string InventoryPath = "ZkLobbyServer/seam-inventory.txt";

        public static int Run(ZkDataContext db, string mode)
        {
            var entities = EntityTypes(db);
            var lines = new List<string>();
            var blocked = 0;

            foreach (var member in Members())
            {
                var problems = Problems(member, entities);
                if (problems.Count == 0) lines.Add("crossable   " + member.Signature);
                else
                {
                    blocked++;
                    lines.Add("BLOCKED     " + member.Signature + "  [" + string.Join("; ", problems) + "]");
                }
            }

            var report = new List<string>
            {
                "# Phase 1: can every member of ILobbyServerApi cross a process boundary?",
                "#",
                "# Generated by `dotnet run --project ZkData.Core -- seam --update`. See",
                "# ZkData.Core/SeamVerification.cs for what 'crossable' means and why it is walked",
                "# transitively rather than read off the signatures.",
                "#",
                "# BLOCKED is not a defect. It is a member whose remote form has not been designed",
                "# yet, and the design is the Phase 1 work.",
                "",
                "members   " + lines.Count,
                "crossable " + (lines.Count - blocked),
                "blocked   " + blocked,
                "",
            };
            report.AddRange(lines);
            var text = string.Join("\n", report) + "\n";

            if (mode == "--update")
            {
                File.WriteAllText(InventoryPath, text);
                Console.WriteLine("recorded " + InventoryPath);
                Console.Write(text);
                return 0;
            }

            if (!File.Exists(InventoryPath))
            {
                Console.WriteLine("missing " + InventoryPath + " - run with --update");
                return 2;
            }

            var recorded = File.ReadAllText(InventoryPath).Replace("\r\n", "\n");
            if (recorded == text)
            {
                Console.WriteLine("the seam is exactly as recorded (" + (lines.Count - blocked)
                                  + " crossable, " + blocked + " blocked)");
                return 0;
            }

            Console.WriteLine("the seam has CHANGED. Recorded vs now:");
            foreach (var diff in Diff(recorded, text)) Console.WriteLine("   " + diff);
            Console.WriteLine();
            Console.WriteLine("If this is the intended change, re-record it with -- seam --update.");
            return 1;
        }

        private static IEnumerable<string> Diff(string recorded, string now)
        {
            var a = recorded.Split('\n');
            var b = now.Split('\n');
            foreach (var line in a.Except(b).Where(x => x.Length > 0)) yield return "- " + line;
            foreach (var line in b.Except(a).Where(x => x.Length > 0)) yield return "+ " + line;
        }

        /// <summary>The entity classes, read off the EF Core model rather than listed by hand.</summary>
        private static HashSet<Type> EntityTypes(ZkDataContext db)
        {
            var types = new HashSet<Type>(db.Model.GetEntityTypes()
                .Select(e => e.ClrType)
                .Where(t => t != null));
            types.Add(typeof(ZkDataContext));
            return types;
        }

        private readonly struct Member
        {
            public Member(string signature, IReadOnlyList<(string Name, Type Type)> types)
            {
                Signature = signature;
                Types = types;
            }

            public string Signature { get; }
            public IReadOnlyList<(string Name, Type Type)> Types { get; }
        }

        private static IEnumerable<Member> Members()
        {
            foreach (var property in typeof(ILobbyServerApi).GetProperties().OrderBy(p => p.Name))
                yield return new Member(property.Name + " { get; }",
                    new[] { ("returns", property.PropertyType) });

            foreach (var method in typeof(ILobbyServerApi).GetMethods()
                         .Where(m => !m.IsSpecialName).OrderBy(m => m.Name))
            {
                var parameters = method.GetParameters();
                var signature = method.Name + "(" + string.Join(", ",
                    parameters.Select(p => Short(p.ParameterType) + " " + p.Name)) + ")";
                var types = parameters.Select(p => (p.Name, p.ParameterType))
                    .Concat(new[] { ("returns", method.ReturnType) }).ToList();
                yield return new Member(signature, types);
            }
        }

        private static List<string> Problems(Member member, HashSet<Type> entities)
        {
            var problems = new List<string>();
            foreach (var (name, type) in member.Types)
            {
                var path = new List<string>();
                if (!Crossable(type, entities, new HashSet<Type>(), path))
                    problems.Add(name + ": " + string.Join(" -> ", path));
            }
            return problems;
        }

        private static bool Crossable(Type type, HashSet<Type> entities, HashSet<Type> seen, List<string> path)
        {
            type = Unwrap(type);
            if (type == null || type == typeof(void) || type == typeof(Task)) return true;
            if (type.IsPrimitive || type.IsEnum) return true;
            if (type == typeof(string) || type == typeof(decimal) || type == typeof(DateTime)
                || type == typeof(TimeSpan) || type == typeof(Guid)) return true;

            if (entities.Contains(type))
            {
                path.Add(Short(type) + (type == typeof(ZkDataContext) ? " (the caller's DbContext)" : " (an EF entity)"));
                return false;
            }

            // A cycle is fine; it is the same type, already being judged further up.
            if (!seen.Add(type)) return true;

            foreach (var field in type.GetFields(BindingFlags.Public | BindingFlags.Instance))
            {
                var inner = new List<string>();
                if (!Crossable(field.FieldType, entities, seen, inner))
                {
                    path.Add(Short(type) + "." + field.Name);
                    path.AddRange(inner);
                    return false;
                }
            }

            foreach (var property in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                if (property.GetIndexParameters().Length > 0) continue;
                var inner = new List<string>();
                if (!Crossable(property.PropertyType, entities, seen, inner))
                {
                    path.Add(Short(type) + "." + property.Name);
                    path.AddRange(inner);
                    return false;
                }
            }

            return true;
        }

        /// <summary>Task&lt;T&gt;, T?, T[] and the usual collections are the shape, not the payload.</summary>
        private static Type Unwrap(Type type)
        {
            while (true)
            {
                if (type.IsArray) { type = type.GetElementType(); continue; }
                if (type.IsGenericType)
                {
                    var definition = type.GetGenericTypeDefinition();
                    if (definition == typeof(Task<>) || definition == typeof(Nullable<>)
                        || definition == typeof(List<>) || definition == typeof(IList<>)
                        || definition == typeof(IEnumerable<>) || definition == typeof(ICollection<>)
                        || definition == typeof(IReadOnlyList<>) || definition == typeof(HashSet<>))
                    {
                        type = type.GetGenericArguments()[0];
                        continue;
                    }
                    if (definition == typeof(Dictionary<,>) || definition == typeof(IDictionary<,>))
                    {
                        // The key is always a primitive in this interface; the value is the payload.
                        type = type.GetGenericArguments()[1];
                        continue;
                    }
                }
                return type;
            }
        }

        private static string Short(Type type)
        {
            type = Nullable.GetUnderlyingType(type) ?? type;
            if (!type.IsGenericType) return type.Name;
            return type.Name.Split('`')[0] + "<"
                   + string.Join(", ", type.GetGenericArguments().Select(Short)) + ">";
        }
    }
}
