// GENERATED by ZkData.Core/generate-column-facets.py - do not edit by hand.
//
// Column facets taken from db/schema/schema.txt, which is what the database actually is.
// EF Core would otherwise pick its own: nvarchar for every string, and no default
// constraints at all. Neither is wrong in the abstract; both are wrong against a database
// that already exists.
//
// EF6's own configuration declares IsUnicode(false) in 19 places. The schema has many
// more, the rest having arrived through 117 migrations - which is why this is read from
// the schema rather than translated from the fluent configuration.
using Microsoft.EntityFrameworkCore;

namespace ZkData
{
    public partial class ZkDataContext
    {
        partial void ConfigureColumnFacets(ModelBuilder modelBuilder)
        {
            // non-Unicode columns (16)
            Facet(modelBuilder, "AccountBattleAwards", "AwardKey", p => p.IsUnicode(false));
            Facet(modelBuilder, "Accounts", "Aliases", p => p.IsUnicode(false));
            Facet(modelBuilder, "Accounts", "Country", p => p.IsUnicode(false));
            Facet(modelBuilder, "Accounts", "Name", p => p.IsUnicode(false));
            Facet(modelBuilder, "CampaignPlanets", "Name", p => p.IsUnicode(false));
            Facet(modelBuilder, "Clans", "ClanName", p => p.IsUnicode(false));
            Facet(modelBuilder, "Clans", "Description", p => p.IsUnicode(false));
            Facet(modelBuilder, "Clans", "Password", p => p.IsUnicode(false));
            Facet(modelBuilder, "Clans", "Shortcut", p => p.IsUnicode(false));
            Facet(modelBuilder, "Factions", "Color", p => p.IsUnicode(false));
            Facet(modelBuilder, "Galaxies", "MatchMakerState", p => p.IsUnicode(false));
            Facet(modelBuilder, "Missions", "TokenCondition", p => p.IsUnicode(false));
            Facet(modelBuilder, "Planets", "Name", p => p.IsUnicode(false));
            Facet(modelBuilder, "ResourceContentFiles", "Md5", p => p.IsUnicode(false));
            Facet(modelBuilder, "ResourceDependencies", "NeedsInternalName", p => p.IsUnicode(false));
            Facet(modelBuilder, "SpringBattles", "EngineGameID", p => p.IsUnicode(false));

            // default constraints (30)
            Facet(modelBuilder, "AccountRatings", "IsRanked", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "AdminLevel", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "CanPlayMultiplayer", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "Accounts", "Cpu", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "DevLevel", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "HasKudos", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "HideCountry", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "IsTourneyController", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "LastChatRead", p => p.HasDefaultValueSql("'1900-01-01T00:00:00.000'"));
            Facet(modelBuilder, "Accounts", "LastLogout", p => p.HasDefaultValueSql("'1900-01-01T00:00:00.000'"));
            Facet(modelBuilder, "Accounts", "PwAttackCharges", p => p.HasDefaultValueSql("(2)"));
            Facet(modelBuilder, "Accounts", "Rank", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Autohosts", "ApplicableRating", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "Autohosts", "CbalEnabled", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "Autohosts", "MaxEvenPlayers", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "FactionTreaties", "TreatyUnableToTradeMode", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Factions", "VictoryPoints", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "ForumCategories", "ForumMode", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "MapPollOutcomes", "Category", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Missions", "RequiredForMultiplayer", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Polls", "IsVisible", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "Punishments", "BanSpecChat", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Punishments", "BanVotes", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Punishments", "MessageOnly", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Resources", "MapSupportLevel", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "SpringBattles", "ApplicableRatings", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "SpringBattles", "IsMatchMaker", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "SpringBattles", "Mode", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "StructureTypes", "IsIngameEvacuable", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "StructureTypes", "OwnerChangeWinsGame", p => p.HasDefaultValueSql("(0)"));
        }

        /// <summary>
        /// Applies a facet by table and column name, skipping quietly if the model has no
        /// such property. Names are the database's, which is what the snapshot records;
        /// where a model property does not match, that is a difference the schema diff
        /// will report rather than something to crash on here.
        /// </summary>
        private static void Facet(ModelBuilder modelBuilder, string table, string column,
            System.Action<Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder> configure)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                var property = entity.FindProperty(column);
                if (property == null) continue;
                configure(modelBuilder.Entity(entity.ClrType).Property(column));
                return;
            }
        }
    }
}
