// GENERATED by ZkData.Core/generate-relationships.py - do not edit by hand.
//
// EF6's fluent configuration, translated. EF Core cannot infer these relationships: two
// navigations on one entity pointing at the same type are ambiguous, and that is where
// model building stops without them.
//
// Translation rules, so the output can be audited against the source:
//   HasMany(x).WithRequired(y)  ->  HasMany(x).WithOne(y).IsRequired(true)
//   HasMany(x).WithOptional(y)  ->  HasMany(x).WithOne(y).IsRequired(false)
//   HasOptional(x).WithMany(y)  ->  HasOne(x).WithMany(y).IsRequired(false)
//   WillCascadeOnDelete(false)  ->  OnDelete(DeleteBehavior.Restrict)
//   WillCascadeOnDelete(true)   ->  OnDelete(DeleteBehavior.Cascade)
//   no WillCascadeOnDelete      ->  EF6's default for that optionality, stated explicitly
//                                   rather than left to EF Core's, which differs
//
// That last rule is the one to check against db/schema/schema.txt: EF6 cascades required
// relationships by default and EF Core does not, so leaving it implicit would silently
// change delete behaviour.
using Microsoft.EntityFrameworkCore;

namespace ZkData
{
    public partial class ZkDataContext
    {
        partial void ConfigureRelationships(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Account>().Property(e => e.Aliases).IsUnicode(false);
            modelBuilder.Entity<Account>().Property(e => e.Country).IsUnicode(false);
            modelBuilder.Entity<Account>().Property(e => e.SteamID).HasPrecision(38, 0);
            modelBuilder.Entity<Account>().HasMany(e => e.AbuseReportsByAccountID).WithOne(e => e.AccountByAccountID).HasForeignKey(e => e.AccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AbuseReportsByReporterAccountID).WithOne(e => e.AccountByReporterAccountID).HasForeignKey(e => e.ReporterAccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AccountBattleAwards).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AccountCampaignJournalProgresses).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AccountForumVotes).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AccountRolesByAccountID).WithOne(e => e.Account).HasForeignKey(e => e.AccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AccountUnlocks).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.CampaignEvents).WithOne(e => e.Account).HasForeignKey(e => e.AccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.Commanders).WithOne(e => e.AccountByAccountID).HasForeignKey(e => e.AccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ContributionsByAccountID).WithOne(e => e.AccountByAccountID).HasForeignKey(e => e.AccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ContributionsByManuallyAddedAccountID).WithOne(e => e.AccountByManuallyAddedID).HasForeignKey(e => e.ManuallyAddedAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ContributionJars).WithOne(e => e.Account).HasForeignKey(e => e.GuarantorAccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.FactionTreatiesByProposingAccount).WithOne(e => e.AccountByProposingAccountID).HasForeignKey(e => e.ProposingAccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.FactionTreatiesByAcceptedAccountID).WithOne(e => e.AccountByAcceptedAccountID).HasForeignKey(e => e.AcceptedAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ForumLastReads).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ForumPostEdits).WithOne(e => e.Account).HasForeignKey(e => e.EditorAccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ForumThreads).WithOne(e => e.AccountByCreatedAccountID).HasForeignKey(e => e.CreatedAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ForumThreadsByLastPostAccountID).WithOne(e => e.AccountByLastPostAccountID).HasForeignKey(e => e.LastPostAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ForumThreadLastReads).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.KudosPurchases).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.Missions).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.MissionScores).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.News).WithOne(e => e.Account).HasForeignKey(e => e.AuthorAccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.Planets).WithOne(e => e.Account).HasForeignKey(e => e.OwnerAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.PlanetOwnerHistories).WithOne(e => e.Account).HasForeignKey(e => e.OwnerAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.PlanetStructures).WithOne(e => e.Account).HasForeignKey(e => e.OwnerAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AccountPlanets).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.PollsByRoleTargetAccountID).WithOne(e => e.AccountByRoleTargetAccountID).HasForeignKey(e => e.RoleTargetAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.PollsByCreatedAccountID).WithOne(e => e.CreatedAccount).HasForeignKey(e => e.CreatedAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.PollVotes).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.PunishmentsByAccountID).WithOne(e => e.AccountByAccountID).HasForeignKey(e => e.AccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.PunishmentsByCreatedAccountID).WithOne(e => e.AccountByCreatedAccountID).HasForeignKey(e => e.CreatedAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.Ratings).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AccountRatings).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<Account>().HasMany(e => e.Resources).WithOne(e => e.Account).HasForeignKey(e => e.TaggedByAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.MapRatings).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.SpringBattles).WithOne(e => e.Account).HasForeignKey(e => e.HostAccountID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.SpringBattlePlayers).WithOne(e => e.Account).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasOne(e => e.Clan).WithMany(e => e.Accounts).HasForeignKey(e => e.ClanID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.ForumPosts).WithOne(e => e.Account).HasForeignKey(e => e.AuthorAccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Account>().HasMany(e => e.AccountMapBans).WithOne(e => e.Account).HasForeignKey(e => e.AccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<AccountBattleAward>().Property(e => e.AwardKey).IsUnicode(false);
            modelBuilder.Entity<Campaign>().HasMany(e => e.AccountCampaignJournalProgresses).WithOne(e => e.Campaign).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Campaign>().HasMany(e => e.AccountCampaignProgresses).WithOne(e => e.Campaign).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Campaign>().HasMany(e => e.AccountCampaignVars).WithOne(e => e.Campaign).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Campaign>().HasMany(e => e.CampaignEvents).WithOne(e => e.Campaign).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Campaign>().HasMany(e => e.CampaignJournalVars).WithOne(e => e.Campaign).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Campaign>().HasMany(e => e.CampaignLinks).WithOne(e => e.Campaign).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Campaign>().HasMany(e => e.CampaignPlanetVars).WithOne(e => e.Campaign).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Campaign>().HasMany(e => e.CampaignVars).WithOne(e => e.Campaign).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CampaignLink>().HasKey(x => new { x.CampaignID, x.PlanetToUnlockID, x.UnlockingPlanetID });
            modelBuilder.Entity<CampaignJournal>().HasMany(e => e.AccountCampaignJournalProgress).WithOne(e => e.CampaignJournal).HasForeignKey(e => new { e.CampaignID, e.JournalID }).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CampaignJournal>().HasMany(e => e.CampaignJournalVars).WithOne(e => e.CampaignJournal).HasForeignKey(e => new { e.CampaignID, e.JournalID }).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CampaignPlanet>().HasKey(x => new { x.CampaignID, x.PlanetID });
            modelBuilder.Entity<CampaignPlanet>().Property(e => e.Name).IsUnicode(false);
            modelBuilder.Entity<CampaignPlanet>().HasMany(e => e.CampaignEvents).WithOne(e => e.CampaignPlanet).HasForeignKey(e => new { e.CampaignID, e.PlanetID }).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<CampaignPlanet>().HasMany(e => e.CampaignLinksByPlanetToUnlock).WithOne(e => e.PlanetToUnlock).HasForeignKey(e => new { e.CampaignID, e.PlanetToUnlockID }).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CampaignPlanet>().HasMany(e => e.CampaignLinksByUnlockingPlanet).WithOne(e => e.UnlockingPlanet).HasForeignKey(e => new { e.CampaignID, e.UnlockingPlanetID }).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CampaignVar>().HasMany(e => e.AccountCampaignVars).WithOne(e => e.CampaignVar).HasForeignKey(e => new { e.CampaignID, e.VarID }).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CampaignVar>().HasMany(e => e.CampaignJournalVars).WithOne(e => e.CampaignVar).HasForeignKey(e => new { e.CampaignID, e.RequiredVarID }).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CampaignVar>().HasMany(e => e.CampaignPlanetVars).WithOne(e => e.CampaignVar).HasForeignKey(e => new { e.CampaignID, e.RequiredVarID }).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Clan>().Property(e => e.ClanName).IsUnicode(false);
            modelBuilder.Entity<Clan>().Property(e => e.Description).IsUnicode(false);
            modelBuilder.Entity<Clan>().Property(e => e.Password).IsUnicode(false);
            modelBuilder.Entity<Clan>().Property(e => e.Shortcut).IsUnicode(false);
            modelBuilder.Entity<Clan>().HasMany(e => e.AccountRoles).WithOne(e => e.Clan).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<Clan>().HasMany(e => e.ForumThreads).WithOne(e => e.Clan).HasForeignKey(e => e.RestrictedClanID).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<Clan>().HasMany(e => e.PlanetOwnerHistories).WithOne(e => e.Clan).HasForeignKey(e => e.OwnerClanID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Clan>().HasMany(e => e.Polls).WithOne(e => e.Clan).HasForeignKey(e => e.RestrictClanID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CommanderDecorationSlot>().HasMany(e => e.CommanderDecorations).WithOne(e => e.CommanderDecorationSlot).HasForeignKey(e => e.SlotID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<CommanderSlot>().HasMany(e => e.CommanderModules).WithOne(e => e.CommanderSlot).HasForeignKey(e => e.SlotID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().Property(e => e.Color).IsUnicode(false);
            modelBuilder.Entity<Faction>().HasMany(e => e.FactionTreatiesByProposingFaction).WithOne(e => e.FactionByProposingFactionID).HasForeignKey(e => e.ProposingFactionID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().HasMany(e => e.FactionTreatiesByAcceptingFaction).WithOne(e => e.FactionByAcceptingFactionID).HasForeignKey(e => e.AcceptingFactionID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().HasMany(e => e.Planets).WithOne(e => e.Faction).HasForeignKey(e => e.OwnerFactionID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().HasMany(e => e.PlanetFactions).WithOne(e => e.Faction).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().HasMany(e => e.PlanetOwnerHistories).WithOne(e => e.Faction).HasForeignKey(e => e.OwnerFactionID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().HasMany(e => e.Polls).WithOne(e => e.Faction).HasForeignKey(e => e.RestrictFactionID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().HasMany(e => e.RoleTypes).WithOne(e => e.Faction).HasForeignKey(e => e.RestrictFactionID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().HasMany(e => e.TreatyEffectsByGivingFactionID).WithOne(e => e.FactionByGivingFactionID).HasForeignKey(e => e.GivingFactionID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Faction>().HasMany(e => e.TreatyEffectsByReceivingFactionID).WithOne(e => e.FactionByReceivingFactionID).HasForeignKey(e => e.ReceivingFactionID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<ForumCategory>().HasMany(e => e.ChildForumCategories).WithOne(e => e.ParentForumCategory).HasForeignKey(e => e.ParentForumCategoryID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<ForumCategory>().HasMany(e => e.ForumLastReads).WithOne(e => e.ForumCategory).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<ForumCategory>().HasMany(e => e.ForumThreads).WithOne(e => e.ForumCategory).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<ForumThread>().HasMany(e => e.Clans).WithOne(e => e.ForumThread).HasForeignKey(e => e.ForumThreadID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<ForumThread>().HasMany(e => e.Missions).WithOne(e => e.ForumThread).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<ForumThread>().HasMany(e => e.News).WithOne(e => e.ForumThread).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<ForumThread>().HasMany(e => e.ForumPosts).WithOne(e => e.ForumThread).HasForeignKey(e => e.ForumThreadID).IsRequired(true).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<Galaxy>().Property(e => e.MatchMakerState).IsUnicode(false);
            modelBuilder.Entity<Mission>().Property(e => e.Description).IsUnicode(false);
            modelBuilder.Entity<Mission>().Property(e => e.DescriptionStory).IsUnicode(false);
            modelBuilder.Entity<Mission>().Property(e => e.TokenCondition).IsUnicode(false);
            modelBuilder.Entity<Mission>().HasMany(e => e.CampaignPlanets).WithOne(e => e.Mission).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Mission>().HasMany(e => e.Ratings).WithOne(e => e.Mission).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<Mission>().HasMany(e => e.Resources).WithOne(e => e.Mission).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<News>().Property(e => e.Text).IsUnicode(false);
            modelBuilder.Entity<CampaignEvent>().HasOne(x => x.Campaign).WithMany(x => x.CampaignEvents).HasForeignKey(x => x.CampaignID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Planet>().Property(e => e.Name).IsUnicode(false);
            modelBuilder.Entity<Planet>().HasMany(e => e.AccountPlanets).WithOne(e => e.Planet).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Planet>().HasMany(e => e.LinksByPlanetID1).WithOne(e => e.PlanetByPlanetID1).HasForeignKey(e => e.PlanetID1).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Planet>().HasMany(e => e.LinksByPlanetID2).WithOne(e => e.PlanetByPlanetID2).HasForeignKey(e => e.PlanetID2).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Planet>().HasMany(e => e.PlanetFactions).WithOne(e => e.Planet).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Planet>().HasMany(e => e.PlanetStructures).WithOne(e => e.Planet).HasForeignKey(e => e.PlanetID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Planet>().HasMany(e => e.PlanetStructuresByTargetPlanetID).WithOne(e => e.PlanetByTargetPlanetID).HasForeignKey(e => e.TargetPlanetID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<PollOption>().HasMany(e => e.PollVotes).WithOne(e => e.PollOption).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Resource>().HasMany(e => e.Planets).WithOne(e => e.Resource).HasForeignKey(e => e.MapResourceID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Resource>().HasMany(e => e.SpringBattlesByModID).WithOne(e => e.ResourceByModResourceID).HasForeignKey(e => e.ModResourceID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Resource>().HasMany(e => e.SpringBattlesByMapResourceID).WithOne(e => e.ResourceByMapResourceID).HasForeignKey(e => e.MapResourceID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Resource>().HasMany(e => e.BansByAccountID).WithOne(e => e.Resource).HasForeignKey(e => e.BannedMapResourceID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<ResourceContentFile>().Property(e => e.Md5).IsFixedLength().IsUnicode(false);
            modelBuilder.Entity<ResourceContentFile>().Property(e => e.Links).IsUnicode(false);
            modelBuilder.Entity<ResourceDependency>().Property(e => e.NeedsInternalName).IsUnicode(false);
            modelBuilder.Entity<RoleType>().HasMany(e => e.Polls).WithOne(e => e.RoleType).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<RoleType>().HasMany(e => e.RoleTypeHierarchiesByMasterRoleTypeID).WithOne(e => e.MasterRoleType).HasForeignKey(e => e.MasterRoleTypeID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<RoleType>().HasMany(e => e.RoleTypeHierarchiesBySlaveRoleTypeID).WithOne(e => e.SlaveRoleType).HasForeignKey(e => e.SlaveRoleTypeID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<SpringBattle>().Property(e => e.EngineGameID).IsUnicode(false);
            modelBuilder.Entity<StructureType>().HasMany(e => e.PlanetStructures).WithOne(e => e.StructureType).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<TreatyEffectType>().HasMany(e => e.TreatyEffects).WithOne(e => e.TreatyEffectType).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Unlock>().HasMany(e => e.Commanders).WithOne(e => e.Unlock).HasForeignKey(e => e.ChassisUnlockID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Unlock>().HasMany(e => e.CommanderDecorations).WithOne(e => e.Unlock).HasForeignKey(e => e.DecorationUnlockID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Unlock>().HasMany(e => e.CommanderModules).WithOne(e => e.Unlock).HasForeignKey(e => e.ModuleUnlockID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<Unlock>().HasMany(e => e.KudosPurchases).WithOne(e => e.Unlock).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<Unlock>().HasMany(e => e.StructureTypes).WithOne(e => e.Unlock).HasForeignKey(e => e.EffectUnlockID).IsRequired(false).OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<Unlock>().HasMany(e => e.ChildUnlocks).WithOne(e => e.ParentUnlock).HasForeignKey(e => e.RequiredUnlockID).IsRequired(false).OnDelete(DeleteBehavior.Restrict);
            modelBuilder.Entity<AccountRelation>().HasOne(x => x.Target).WithMany(x => x.RelalationsByTarget).HasForeignKey(x => x.TargetAccountID).IsRequired(true).OnDelete(DeleteBehavior.Restrict);

            // Not translated here - done by hand in
            // ZkDataContext.RelationshipsByHand.cs. Listed so the two files can be
            // checked against each other:
            //   unrecognised shape: HasRequired
            //     modelBuilder.Entity<AccountMapBan>() .HasRequired(e => e.Resource)
            //   no foreign key stated and CampaignPlanet has a composite key
            //     modelBuilder.Entity<CampaignPlanet>() .HasMany(e => e.AccountCampaignProgress) .WithRequired(e => e.CampaignPlanet) .WillCascadeOnDelete(false)
            //   no foreign key stated and CampaignPlanet has a composite key
            //     modelBuilder.Entity<CampaignPlanet>().HasMany(e => e.CampaignJournals).WithOptional(e => e.CampaignPlanet)
            //   no foreign key stated and CampaignPlanet has a composite key
            //     modelBuilder.Entity<CampaignPlanet>() .HasMany(e => e.CampaignPlanetVars) .WithRequired(e => e.CampaignPlanet) .WillCascadeOnDelete(false)
            //   many-to-many with Map/ToTable needs UsingEntity
            //     modelBuilder.Entity<Clan>() .HasMany(e => e.Events) .WithMany(e => e.Clans) .Map(m => m.ToTable("EventClan").MapLeftKey("ClanID").MapRightKey("EventID
            //   many-to-many with Map/ToTable needs UsingEntity
            //     modelBuilder.Entity<Event>() .HasMany(e => e.Accounts) .WithMany(e => e.Events) .Map(m => m.ToTable("EventAccount").MapLeftKey("EventID").MapRightKey(
            //   many-to-many with Map/ToTable needs UsingEntity
            //     modelBuilder.Entity<Event>() .HasMany(e => e.Factions) .WithMany(e => e.Events) .Map(m => m.ToTable("EventFaction").MapLeftKey("EventID").MapRightKey(
            //   many-to-many with Map/ToTable needs UsingEntity
            //     modelBuilder.Entity<Event>() .HasMany(e => e.Planets) .WithMany(e => e.Events) .Map(m => m.ToTable("EventPlanet").MapLeftKey("EventID").MapRightKey("P
            //   many-to-many with Map/ToTable needs UsingEntity
            //     modelBuilder.Entity<Event>() .HasMany(e => e.SpringBattles) .WithMany(e => e.Events) .Map(m => m.ToTable("EventSpringBattle").MapLeftKey("EventID").Ma
            //   unrecognised shape: HasOptional WithRequired
            //     modelBuilder.Entity<Unlock>() .HasOptional(e => e.CommanderDecorationIcon) .WithRequired(e => e.Unlock)
        }
    }
}
