// GENERATED by ZkData.Core/generate-column-facets.py - do not edit by hand.
//
// Column facets taken from db/schema/schema.txt, which is what the database actually is.
// EF Core would otherwise pick its own: nvarchar for every string, and no default
// constraints at all. Neither is wrong in the abstract; both are wrong against a database
// that already exists.
//
// EF6's own configuration declares IsUnicode(false) in 19 places. The schema has many
// more, the rest having arrived through 117 migrations - which is why this is read from
// the schema rather than translated from the fluent configuration.
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ZkData
{
    public partial class ZkDataContext
    {
        partial void ConfigureColumnFacets(ModelBuilder modelBuilder)
        {
            // non-Unicode columns (16)
            Facet(modelBuilder, "AccountBattleAwards", "AwardKey", p => p.IsUnicode(false));
            Facet(modelBuilder, "Accounts", "Aliases", p => p.IsUnicode(false));
            Facet(modelBuilder, "Accounts", "Country", p => p.IsUnicode(false));
            Facet(modelBuilder, "Accounts", "Name", p => p.IsUnicode(false));
            Facet(modelBuilder, "CampaignPlanets", "Name", p => p.IsUnicode(false));
            Facet(modelBuilder, "Clans", "ClanName", p => p.IsUnicode(false));
            Facet(modelBuilder, "Clans", "Description", p => p.IsUnicode(false));
            Facet(modelBuilder, "Clans", "Password", p => p.IsUnicode(false));
            Facet(modelBuilder, "Clans", "Shortcut", p => p.IsUnicode(false));
            Facet(modelBuilder, "Factions", "Color", p => p.IsUnicode(false));
            Facet(modelBuilder, "Galaxies", "MatchMakerState", p => p.IsUnicode(false));
            Facet(modelBuilder, "Missions", "TokenCondition", p => p.IsUnicode(false));
            Facet(modelBuilder, "Planets", "Name", p => p.IsUnicode(false));
            Facet(modelBuilder, "ResourceContentFiles", "Md5", p => p.IsUnicode(false));
            Facet(modelBuilder, "ResourceDependencies", "NeedsInternalName", p => p.IsUnicode(false));
            Facet(modelBuilder, "SpringBattles", "EngineGameID", p => p.IsUnicode(false));

            // string lengths, from the schema (142). Some disagree with the
            // entity attributes - migrations widened columns without updating them.
            Facet(modelBuilder, "AbuseReports", "Text", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "AccountBattleAwards", "AwardDescription", p => p.HasMaxLength(500));
            Facet(modelBuilder, "AccountBattleAwards", "AwardKey", p => p.HasMaxLength(50));
            Facet(modelBuilder, "AccountCampaignVars", "Value", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "AccountIPs", "IP", p => p.HasMaxLength(50));
            Facet(modelBuilder, "AccountUserIDs", "InstallID", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Accounts", "Aliases", p => p.HasMaxLength(8000));
            Facet(modelBuilder, "Accounts", "Avatar", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Accounts", "Country", p => p.HasMaxLength(5));
            Facet(modelBuilder, "Accounts", "Email", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Accounts", "LastPubKey", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "Accounts", "LobbyVersion", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Accounts", "Name", p => p.HasMaxLength(2000));
            Facet(modelBuilder, "Accounts", "PasswordBcrypt", p => p.HasMaxLength(150));
            Facet(modelBuilder, "Accounts", "PurchasedDlc", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "Accounts", "SpecialNote", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Accounts", "SteamName", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Autohosts", "MapName", p => p.HasMaxLength(255));
            Facet(modelBuilder, "Autohosts", "ModName", p => p.HasMaxLength(255));
            Facet(modelBuilder, "Autohosts", "Title", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Avatars", "AvatarName", p => p.HasMaxLength(50));
            Facet(modelBuilder, "BlockedCompanies", "Comment", p => p.HasMaxLength(500));
            Facet(modelBuilder, "BlockedCompanies", "CompanyName", p => p.HasMaxLength(500));
            Facet(modelBuilder, "BlockedHosts", "Comment", p => p.HasMaxLength(500));
            Facet(modelBuilder, "BlockedHosts", "HostName", p => p.HasMaxLength(500));
            Facet(modelBuilder, "CampaignEvents", "PlainText", p => p.HasMaxLength(4000));
            Facet(modelBuilder, "CampaignEvents", "Text", p => p.HasMaxLength(4000));
            Facet(modelBuilder, "CampaignJournalVars", "RequiredValue", p => p.HasMaxLength(500));
            Facet(modelBuilder, "CampaignJournals", "Category", p => p.HasMaxLength(1000));
            Facet(modelBuilder, "CampaignJournals", "Text", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "CampaignJournals", "Title", p => p.HasMaxLength(50));
            Facet(modelBuilder, "CampaignPlanetVars", "RequiredValue", p => p.HasMaxLength(500));
            Facet(modelBuilder, "CampaignPlanets", "Description", p => p.HasMaxLength(4000));
            Facet(modelBuilder, "CampaignPlanets", "DescriptionStory", p => p.HasMaxLength(4000));
            Facet(modelBuilder, "CampaignPlanets", "DisplayedMap", p => p.HasMaxLength(100));
            Facet(modelBuilder, "CampaignPlanets", "Name", p => p.HasMaxLength(50));
            Facet(modelBuilder, "CampaignVars", "Description", p => p.HasMaxLength(4000));
            Facet(modelBuilder, "CampaignVars", "KeyString", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Campaigns", "Description", p => p.HasMaxLength(2000));
            Facet(modelBuilder, "Campaigns", "MapImageName", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Campaigns", "Name", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Clans", "ClanName", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Clans", "Description", p => p.HasMaxLength(500));
            Facet(modelBuilder, "Clans", "Password", p => p.HasMaxLength(20));
            Facet(modelBuilder, "Clans", "SecretTopic", p => p.HasMaxLength(500));
            Facet(modelBuilder, "Clans", "Shortcut", p => p.HasMaxLength(6));
            Facet(modelBuilder, "Commanders", "Name", p => p.HasMaxLength(200));
            Facet(modelBuilder, "ContributionJars", "Description", p => p.HasMaxLength(500));
            Facet(modelBuilder, "ContributionJars", "Name", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Contributions", "Comment", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Contributions", "Email", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Contributions", "ItemCode", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Contributions", "ItemName", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Contributions", "Name", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Contributions", "OriginalCurrency", p => p.HasMaxLength(5));
            Facet(modelBuilder, "Contributions", "PayPalTransactionID", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Contributions", "RedeemCode", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Events", "PlainText", p => p.HasMaxLength(4000));
            Facet(modelBuilder, "Events", "Text", p => p.HasMaxLength(4000));
            Facet(modelBuilder, "FactionTreaties", "TreatyNote", p => p.HasMaxLength(1000));
            Facet(modelBuilder, "Factions", "Color", p => p.HasMaxLength(20));
            Facet(modelBuilder, "Factions", "Name", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Factions", "SecretTopic", p => p.HasMaxLength(500));
            Facet(modelBuilder, "Factions", "Shortcut", p => p.HasMaxLength(50));
            Facet(modelBuilder, "ForumCategories", "Title", p => p.HasMaxLength(500));
            Facet(modelBuilder, "ForumPostEdits", "NewText", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "ForumPostEdits", "OriginalText", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "ForumPosts", "Text", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "ForumThreads", "Title", p => p.HasMaxLength(300));
            Facet(modelBuilder, "ForumThreads", "WikiKey", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Galaxies", "EndMessage", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "Galaxies", "ImageName", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Galaxies", "MatchMakerState", p => p.HasColumnType("varchar(max)"));
            Facet(modelBuilder, "GameModes", "DisplayName", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "GameModes", "GameModeJson", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "GameModes", "ShortName", p => p.HasMaxLength(64));
            Facet(modelBuilder, "LobbyChannelTopics", "Author", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "LobbyChannelTopics", "ChannelName", p => p.HasMaxLength(200));
            Facet(modelBuilder, "LobbyChannelTopics", "Topic", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "LobbyChatHistories", "Target", p => p.HasMaxLength(255));
            Facet(modelBuilder, "LobbyChatHistories", "Text", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "LobbyChatHistories", "User", p => p.HasMaxLength(255));
            Facet(modelBuilder, "LobbyNews", "ImageExtension", p => p.HasMaxLength(50));
            Facet(modelBuilder, "LobbyNews", "Text", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "LobbyNews", "Title", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "LobbyNews", "Url", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "LogEntries", "Message", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "MiscVars", "VarName", p => p.HasMaxLength(200));
            Facet(modelBuilder, "MiscVars", "VarValue", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "Missions", "ManualDependencies", p => p.HasMaxLength(1000));
            Facet(modelBuilder, "Missions", "Map", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Missions", "MissionEditorVersion", p => p.HasMaxLength(20));
            Facet(modelBuilder, "Missions", "Mod", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Missions", "ModOptions", p => p.HasMaxLength(4000));
            Facet(modelBuilder, "Missions", "ModRapidTag", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Missions", "Name", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Missions", "ScoringMethod", p => p.HasMaxLength(500));
            Facet(modelBuilder, "Missions", "Script", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "Missions", "SpringVersion", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Missions", "TokenCondition", p => p.HasMaxLength(500));
            Facet(modelBuilder, "Missions", "TopScoreLine", p => p.HasMaxLength(100));
            Facet(modelBuilder, "News", "ImageContentType", p => p.HasMaxLength(50));
            Facet(modelBuilder, "News", "ImageExtension", p => p.HasMaxLength(50));
            Facet(modelBuilder, "News", "Title", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Planets", "Name", p => p.HasMaxLength(50));
            Facet(modelBuilder, "PollOptions", "OptionText", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Polls", "QuestionText", p => p.HasMaxLength(500));
            Facet(modelBuilder, "Punishments", "BanIP", p => p.HasMaxLength(1000));
            Facet(modelBuilder, "Punishments", "InstallID", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "Punishments", "Reason", p => p.HasMaxLength(1000));
            Facet(modelBuilder, "ResourceContentFiles", "FileName", p => p.HasMaxLength(255));
            Facet(modelBuilder, "ResourceContentFiles", "Md5", p => p.HasMaxLength(32));
            Facet(modelBuilder, "ResourceDependencies", "NeedsInternalName", p => p.HasMaxLength(250));
            Facet(modelBuilder, "Resources", "AuthorName", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Resources", "InternalName", p => p.HasMaxLength(255));
            Facet(modelBuilder, "Resources", "MapPlanetWarsIcon", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Resources", "MapSpringieCommands", p => p.HasMaxLength(2000));
            Facet(modelBuilder, "Resources", "MapTags", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "Resources", "RapidTag", p => p.HasMaxLength(100));
            Facet(modelBuilder, "RoleTypes", "Description", p => p.HasMaxLength(500));
            Facet(modelBuilder, "RoleTypes", "Name", p => p.HasMaxLength(50));
            Facet(modelBuilder, "SpringBattleBots", "BotAI", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "SpringBattleBots", "BotName", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "SpringBattles", "EngineGameID", p => p.HasMaxLength(64));
            Facet(modelBuilder, "SpringBattles", "EngineVersion", p => p.HasMaxLength(100));
            Facet(modelBuilder, "SpringBattles", "ReplayFileName", p => p.HasMaxLength(500));
            Facet(modelBuilder, "SpringBattles", "Title", p => p.HasMaxLength(200));
            Facet(modelBuilder, "SpringFilesUnitsyncAttempts", "FileName", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "StructureTypes", "Description", p => p.HasMaxLength(250));
            Facet(modelBuilder, "StructureTypes", "DisabledMapIcon", p => p.HasMaxLength(50));
            Facet(modelBuilder, "StructureTypes", "EffectBots", p => p.HasMaxLength(100));
            Facet(modelBuilder, "StructureTypes", "IngameUnitName", p => p.HasMaxLength(50));
            Facet(modelBuilder, "StructureTypes", "MapIcon", p => p.HasMaxLength(50));
            Facet(modelBuilder, "StructureTypes", "Name", p => p.HasMaxLength(50));
            Facet(modelBuilder, "TreatyEffectTypes", "Description", p => p.HasMaxLength(200));
            Facet(modelBuilder, "TreatyEffectTypes", "Name", p => p.HasMaxLength(50));
            Facet(modelBuilder, "Unlocks", "Code", p => p.HasMaxLength(100));
            Facet(modelBuilder, "Unlocks", "Description", p => p.HasMaxLength(1000));
            Facet(modelBuilder, "Unlocks", "LimitForChassis", p => p.HasMaxLength(500));
            Facet(modelBuilder, "Unlocks", "Name", p => p.HasMaxLength(200));
            Facet(modelBuilder, "Unlocks", "RequiredInstalledUnlockIDs", p => p.HasColumnType("nvarchar(max)"));
            Facet(modelBuilder, "Words", "Text", p => p.HasMaxLength(100));

            // default constraints (51)
            Facet(modelBuilder, "AccountRatings", "IsRanked", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "AdminLevel", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "CanPlayMultiplayer", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "Accounts", "Cpu", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "DevLevel", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "HasKudos", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "HideCountry", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "IsTourneyController", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Accounts", "LastChatRead", p => p.HasDefaultValueSql("'1900-01-01T00:00:00.000'"));
            Facet(modelBuilder, "Accounts", "LastLogout", p => p.HasDefaultValueSql("'1900-01-01T00:00:00.000'"));
            Facet(modelBuilder, "Accounts", "PwAttackCharges", p => p.HasDefaultValueSql("(2)"));
            Facet(modelBuilder, "Accounts", "Rank", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Autohosts", "ApplicableRating", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "Autohosts", "CbalEnabled", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "Autohosts", "MaxEvenPlayers", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MapVoteFractionOfPopularMaps", p => p.HasDefaultValueSql("(0.5)"));
            Facet(modelBuilder, "DynamicConfigs", "MaximumBattlePlayers", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MaximumStatLimitedBattlePlayers", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MinimumPlayersForStdevBalance", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "Mm1v1MinimumWinChance", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MmEloBonusMultiplier", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MmMinimumMinutesBetweenGames", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MmMinimumMinutesBetweenSuggestions", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MmSizeGrowthTime", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MmTeamsMinimumWinChance", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "MmWidthReductionForParties", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "PwAttackChargesCooldownMinutes", p => p.HasDefaultValueSql("(60)"));
            Facet(modelBuilder, "DynamicConfigs", "PwAttackChargesMax", p => p.HasDefaultValueSql("(2)"));
            Facet(modelBuilder, "DynamicConfigs", "PwAttackChargesPassiveLimit", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "DynamicConfigs", "PwAttackOptionCount", p => p.HasDefaultValueSql("(6)"));
            Facet(modelBuilder, "DynamicConfigs", "PwAttackPhaseMinutes", p => p.HasDefaultValueSql("(2)"));
            Facet(modelBuilder, "DynamicConfigs", "PwBomberMinimumIpFloor", p => p.HasDefaultValueSql("(5)"));
            Facet(modelBuilder, "DynamicConfigs", "PwBomberSelfIpRate", p => p.HasDefaultValueSql("(0.5)"));
            Facet(modelBuilder, "DynamicConfigs", "PwDefendPhaseMinutes", p => p.HasDefaultValueSql("(2)"));
            Facet(modelBuilder, "DynamicConfigs", "StdevBalanceWeight", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "DynamicConfigs", "TimeQueueEnabled", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "FactionTreaties", "TreatyUnableToTradeMode", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Factions", "VictoryPoints", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "ForumCategories", "ForumMode", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "MapPollOutcomes", "Category", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Missions", "RequiredForMultiplayer", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Polls", "IsVisible", p => p.HasDefaultValueSql("(1)"));
            Facet(modelBuilder, "Punishments", "BanSpecChat", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Punishments", "BanVotes", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Punishments", "MessageOnly", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "Resources", "MapSupportLevel", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "SpringBattles", "ApplicableRatings", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "SpringBattles", "IsMatchMaker", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "SpringBattles", "Mode", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "StructureTypes", "IsIngameEvacuable", p => p.HasDefaultValueSql("(0)"));
            Facet(modelBuilder, "StructureTypes", "OwnerChangeWinsGame", p => p.HasDefaultValueSql("(0)"));

            // indexes the database has that EF Core would not create (176).
            // EF6 indexed foreign key columns even when they were already the leading
            // columns of the primary key; EF Core treats those as redundant and skips
            // them. Declaring them keeps the schema identical.
            Index(modelBuilder, "AbuseReports", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AbuseReports", new[] { "ReporterAccountID" }, false, null);
            Index(modelBuilder, "AccountBattleAwards", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountBattleAwards", new[] { "SpringBattleID" }, false, null);
            Index(modelBuilder, "AccountCampaignJournalProgresses", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountCampaignJournalProgresses", new[] { "CampaignID", "JournalID" }, false, null);
            Index(modelBuilder, "AccountCampaignProgresses", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountCampaignProgresses", new[] { "CampaignID" }, false, null);
            Index(modelBuilder, "AccountCampaignProgresses", new[] { "CampaignID", "PlanetID" }, false, null);
            Index(modelBuilder, "AccountCampaignVars", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountCampaignVars", new[] { "CampaignID", "VarID" }, false, null);
            Index(modelBuilder, "AccountForumVotes", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountForumVotes", new[] { "ForumPostID" }, false, null);
            Index(modelBuilder, "AccountIPs", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountMapBans", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountPlanets", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountPlanets", new[] { "PlanetID" }, false, null);
            Index(modelBuilder, "AccountRatings", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountRatings", new[] { "Elo" }, false, null);
            Index(modelBuilder, "AccountRatings", new[] { "IsRanked" }, false, null);
            Index(modelBuilder, "AccountRatings", new[] { "LadderElo" }, false, null);
            Index(modelBuilder, "AccountRatings", new[] { "RealElo" }, false, null);
            Index(modelBuilder, "AccountRelations", new[] { "OwnerAccountID" }, false, null);
            Index(modelBuilder, "AccountRelations", new[] { "TargetAccountID" }, false, null);
            Index(modelBuilder, "AccountRoles", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountRoles", new[] { "ClanID" }, false, null);
            Index(modelBuilder, "AccountRoles", new[] { "FactionID" }, false, null);
            Index(modelBuilder, "AccountRoles", new[] { "RoleTypeID" }, false, null);
            Index(modelBuilder, "AccountUnlocks", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "AccountUnlocks", new[] { "UnlockID" }, false, null);
            Index(modelBuilder, "AccountUserIDs", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "Accounts", new[] { "ClanID" }, false, null);
            Index(modelBuilder, "Accounts", new[] { "FactionID" }, false, null);
            Index(modelBuilder, "Accounts", new[] { "Name" }, true, null);
            Index(modelBuilder, "Accounts", new[] { "SteamID" }, true, "([SteamID] IS NOT NULL)");
            Index(modelBuilder, "CampaignEvents", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "CampaignEvents", new[] { "CampaignID" }, false, null);
            Index(modelBuilder, "CampaignEvents", new[] { "CampaignID", "PlanetID" }, false, null);
            Index(modelBuilder, "CampaignJournalVars", new[] { "CampaignID", "JournalID" }, false, null);
            Index(modelBuilder, "CampaignJournalVars", new[] { "CampaignID", "RequiredVarID" }, false, null);
            Index(modelBuilder, "CampaignJournals", new[] { "CampaignID" }, false, null);
            Index(modelBuilder, "CampaignJournals", new[] { "CampaignID", "PlanetID" }, false, null);
            Index(modelBuilder, "CampaignLinks", new[] { "CampaignID" }, false, null);
            Index(modelBuilder, "CampaignLinks", new[] { "CampaignID", "PlanetToUnlockID" }, false, null);
            Index(modelBuilder, "CampaignLinks", new[] { "CampaignID", "UnlockingPlanetID" }, false, null);
            Index(modelBuilder, "CampaignPlanetVars", new[] { "CampaignID", "PlanetID" }, false, null);
            Index(modelBuilder, "CampaignPlanetVars", new[] { "CampaignID", "RequiredVarID" }, false, null);
            Index(modelBuilder, "CampaignPlanets", new[] { "CampaignID" }, false, null);
            Index(modelBuilder, "CampaignPlanets", new[] { "MissionID" }, false, null);
            Index(modelBuilder, "CampaignVars", new[] { "CampaignID" }, false, null);
            Index(modelBuilder, "Clans", new[] { "FactionID" }, false, null);
            Index(modelBuilder, "Clans", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "CommanderDecorationIcons", new[] { "DecorationUnlockID" }, false, null);
            Index(modelBuilder, "CommanderDecorations", new[] { "CommanderID" }, false, null);
            Index(modelBuilder, "CommanderDecorations", new[] { "DecorationUnlockID" }, false, null);
            Index(modelBuilder, "CommanderDecorations", new[] { "SlotID" }, false, null);
            Index(modelBuilder, "CommanderModules", new[] { "CommanderID" }, false, null);
            Index(modelBuilder, "CommanderModules", new[] { "ModuleUnlockID" }, false, null);
            Index(modelBuilder, "CommanderModules", new[] { "SlotID" }, false, null);
            Index(modelBuilder, "Commanders", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "Commanders", new[] { "ChassisUnlockID" }, false, null);
            Index(modelBuilder, "ContributionJars", new[] { "GuarantorAccountID" }, false, null);
            Index(modelBuilder, "Contributions", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "Contributions", new[] { "ContributionJarID" }, false, null);
            Index(modelBuilder, "Contributions", new[] { "ManuallyAddedAccountID" }, false, null);
            Index(modelBuilder, "EventAccount", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "EventAccount", new[] { "EventID" }, false, null);
            Index(modelBuilder, "EventClan", new[] { "ClanID" }, false, null);
            Index(modelBuilder, "EventClan", new[] { "EventID" }, false, null);
            Index(modelBuilder, "EventFaction", new[] { "EventID" }, false, null);
            Index(modelBuilder, "EventFaction", new[] { "FactionID" }, false, null);
            Index(modelBuilder, "EventPlanet", new[] { "EventID" }, false, null);
            Index(modelBuilder, "EventPlanet", new[] { "PlanetID" }, false, null);
            Index(modelBuilder, "EventSpringBattle", new[] { "EventID" }, false, null);
            Index(modelBuilder, "EventSpringBattle", new[] { "SpringBattleID" }, false, null);
            Index(modelBuilder, "FactionTreaties", new[] { "AcceptedAccountID" }, false, null);
            Index(modelBuilder, "FactionTreaties", new[] { "AcceptingFactionID" }, false, null);
            Index(modelBuilder, "FactionTreaties", new[] { "ProposingAccountID" }, false, null);
            Index(modelBuilder, "FactionTreaties", new[] { "ProposingFactionID" }, false, null);
            Index(modelBuilder, "ForumCategories", new[] { "ParentForumCategoryID" }, false, null);
            Index(modelBuilder, "ForumLastReads", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "ForumLastReads", new[] { "ForumCategoryID" }, false, null);
            Index(modelBuilder, "ForumPostEdits", new[] { "EditorAccountID" }, false, null);
            Index(modelBuilder, "ForumPostEdits", new[] { "ForumPostID" }, false, null);
            Index(modelBuilder, "ForumPostWords", new[] { "ForumPostID" }, false, null);
            Index(modelBuilder, "ForumPostWords", new[] { "WordID" }, false, null);
            Index(modelBuilder, "ForumPosts", new[] { "AuthorAccountID" }, false, null);
            Index(modelBuilder, "ForumPosts", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "ForumThreadLastReads", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "ForumThreadLastReads", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "ForumThreads", new[] { "CreatedAccountID" }, false, null);
            Index(modelBuilder, "ForumThreads", new[] { "ForumCategoryID" }, false, null);
            Index(modelBuilder, "ForumThreads", new[] { "LastPostAccountID" }, false, null);
            Index(modelBuilder, "ForumThreads", new[] { "RestrictedClanID" }, false, null);
            Index(modelBuilder, "ForumThreads", new[] { "Title" }, false, null);
            Index(modelBuilder, "ForumThreads", new[] { "WikiKey" }, false, null);
            Index(modelBuilder, "Galaxies", new[] { "WinnerFactionID" }, false, null);
            Index(modelBuilder, "GameModes", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "GameModes", new[] { "MaintainerAccountID" }, false, null);
            Index(modelBuilder, "GameModes", new[] { "ShortName" }, true, null);
            Index(modelBuilder, "KudosPurchases", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "KudosPurchases", new[] { "UnlockID" }, false, null);
            Index(modelBuilder, "Links", new[] { "GalaxyID" }, false, null);
            Index(modelBuilder, "Links", new[] { "PlanetID1" }, false, null);
            Index(modelBuilder, "Links", new[] { "PlanetID2" }, false, null);
            Index(modelBuilder, "LobbyChatHistories", new[] { "Target" }, false, null);
            Index(modelBuilder, "LobbyChatHistories", new[] { "Time" }, false, null);
            Index(modelBuilder, "LobbyChatHistories", new[] { "User" }, false, null);
            Index(modelBuilder, "LobbyNews", new[] { "AuthorAccountID" }, false, null);
            Index(modelBuilder, "MapPollOptions", new[] { "MapPollID" }, false, null);
            Index(modelBuilder, "MapPollOptions", new[] { "ResourceID" }, false, null);
            Index(modelBuilder, "MapRatings", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "MapRatings", new[] { "ResourceID" }, false, null);
            Index(modelBuilder, "MissionScores", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "MissionScores", new[] { "MissionID" }, false, null);
            Index(modelBuilder, "Missions", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "Missions", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "Missions", new[] { "Name" }, true, null);
            Index(modelBuilder, "News", new[] { "AuthorAccountID" }, false, null);
            Index(modelBuilder, "News", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "PlanetFactions", new[] { "FactionID" }, false, null);
            Index(modelBuilder, "PlanetFactions", new[] { "PlanetID" }, false, null);
            Index(modelBuilder, "PlanetOwnerHistories", new[] { "OwnerAccountID" }, false, null);
            Index(modelBuilder, "PlanetOwnerHistories", new[] { "OwnerClanID" }, false, null);
            Index(modelBuilder, "PlanetOwnerHistories", new[] { "OwnerFactionID" }, false, null);
            Index(modelBuilder, "PlanetOwnerHistories", new[] { "PlanetID" }, false, null);
            Index(modelBuilder, "PlanetStructures", new[] { "OwnerAccountID" }, false, null);
            Index(modelBuilder, "PlanetStructures", new[] { "PlanetID" }, false, null);
            Index(modelBuilder, "PlanetStructures", new[] { "StructureTypeID" }, false, null);
            Index(modelBuilder, "PlanetStructures", new[] { "TargetPlanetID" }, false, null);
            Index(modelBuilder, "Planets", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "Planets", new[] { "GalaxyID" }, false, null);
            Index(modelBuilder, "Planets", new[] { "MapResourceID" }, false, null);
            Index(modelBuilder, "Planets", new[] { "OwnerAccountID" }, false, null);
            Index(modelBuilder, "Planets", new[] { "OwnerFactionID" }, false, null);
            Index(modelBuilder, "PollOptions", new[] { "PollID" }, false, null);
            Index(modelBuilder, "PollVotes", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "PollVotes", new[] { "OptionID" }, false, null);
            Index(modelBuilder, "PollVotes", new[] { "PollID" }, false, null);
            Index(modelBuilder, "Polls", new[] { "CreatedAccountID" }, false, null);
            Index(modelBuilder, "Polls", new[] { "RestrictClanID" }, false, null);
            Index(modelBuilder, "Polls", new[] { "RestrictFactionID" }, false, null);
            Index(modelBuilder, "Polls", new[] { "RoleTargetAccountID" }, false, null);
            Index(modelBuilder, "Polls", new[] { "RoleTypeID" }, false, null);
            Index(modelBuilder, "Punishments", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "Punishments", new[] { "CreatedAccountID" }, false, null);
            Index(modelBuilder, "Ratings", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "Ratings", new[] { "MissionID" }, false, null);
            Index(modelBuilder, "ResourceContentFiles", new[] { "ResourceID" }, false, null);
            Index(modelBuilder, "ResourceDependencies", new[] { "ResourceID" }, false, null);
            Index(modelBuilder, "Resources", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "Resources", new[] { "InternalName" }, true, null);
            Index(modelBuilder, "Resources", new[] { "MissionID" }, false, null);
            Index(modelBuilder, "Resources", new[] { "RapidTag" }, false, null);
            Index(modelBuilder, "Resources", new[] { "TaggedByAccountID" }, false, null);
            Index(modelBuilder, "RoleTypeHierarchies", new[] { "MasterRoleTypeID" }, false, null);
            Index(modelBuilder, "RoleTypeHierarchies", new[] { "SlaveRoleTypeID" }, false, null);
            Index(modelBuilder, "RoleTypes", new[] { "RestrictFactionID" }, false, null);
            Index(modelBuilder, "SpringBattleBots", new[] { "SpringBattleID" }, false, null);
            Index(modelBuilder, "SpringBattlePlayers", new[] { "AccountID" }, false, null);
            Index(modelBuilder, "SpringBattlePlayers", new[] { "SpringBattleID" }, false, null);
            Index(modelBuilder, "SpringBattles", new[] { "EngineGameID" }, false, null);
            Index(modelBuilder, "SpringBattles", new[] { "ForumThreadID" }, false, null);
            Index(modelBuilder, "SpringBattles", new[] { "HostAccountID" }, false, null);
            Index(modelBuilder, "SpringBattles", new[] { "MapResourceID" }, false, null);
            Index(modelBuilder, "SpringBattles", new[] { "ModResourceID" }, false, null);
            Index(modelBuilder, "SpringBattles", new[] { "ReplayFileName" }, false, null);
            Index(modelBuilder, "SpringBattles", new[] { "StartTime" }, false, null);
            Index(modelBuilder, "StructureTypes", new[] { "EffectUnlockID" }, false, null);
            Index(modelBuilder, "TreatyEffects", new[] { "EffectTypeID" }, false, null);
            Index(modelBuilder, "TreatyEffects", new[] { "FactionTreatyID" }, false, null);
            Index(modelBuilder, "TreatyEffects", new[] { "GivingFactionID" }, false, null);
            Index(modelBuilder, "TreatyEffects", new[] { "PlanetID" }, false, null);
            Index(modelBuilder, "TreatyEffects", new[] { "ReceivingFactionID" }, false, null);
            Index(modelBuilder, "Unlocks", new[] { "RequiredUnlockID" }, false, null);
            Index(modelBuilder, "Words", new[] { "Text" }, true, null);

            // delete behaviour for all 163 foreign keys, 62 of them cascading.
            // Taken from the schema rather than from EF6's configuration: the
            // configuration says nothing for many of them, and inferring EF6's default
            // produces cascade paths SQL Server rejects outright. The database cannot
            // contain a cycle, because it exists.
            Fk(modelBuilder, "AbuseReports", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AbuseReports", new[] { "ReporterAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountBattleAwards", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountBattleAwards", new[] { "SpringBattleID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountCampaignJournalProgresses", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountCampaignJournalProgresses", new[] { "CampaignID", "JournalID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountCampaignJournalProgresses", new[] { "CampaignID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountCampaignProgresses", new[] { "AccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountCampaignProgresses", new[] { "CampaignID", "PlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountCampaignProgresses", new[] { "CampaignID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountCampaignVars", new[] { "AccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountCampaignVars", new[] { "CampaignID", "VarID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountCampaignVars", new[] { "CampaignID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountForumVotes", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountForumVotes", new[] { "ForumPostID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountIPs", new[] { "AccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountMapBans", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountMapBans", new[] { "BannedMapResourceID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountPlanets", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountPlanets", new[] { "PlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountRatings", new[] { "AccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountRelations", new[] { "OwnerAccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountRelations", new[] { "TargetAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountRoles", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountRoles", new[] { "ClanID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountRoles", new[] { "FactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountRoles", new[] { "RoleTypeID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountUnlocks", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "AccountUnlocks", new[] { "UnlockID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "AccountUserIDs", new[] { "AccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Accounts", new[] { "ClanID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Accounts", new[] { "FactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignEvents", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignEvents", new[] { "CampaignID", "PlanetID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "CampaignEvents", new[] { "PlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignJournalVars", new[] { "CampaignID", "JournalID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "CampaignJournalVars", new[] { "CampaignID", "RequiredVarID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignJournalVars", new[] { "CampaignID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignJournals", new[] { "CampaignID", "PlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignJournals", new[] { "CampaignID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "CampaignLinks", new[] { "CampaignID", "PlanetToUnlockID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignLinks", new[] { "CampaignID", "UnlockingPlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignLinks", new[] { "CampaignID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignPlanetVars", new[] { "CampaignID", "PlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignPlanetVars", new[] { "CampaignID", "RequiredVarID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignPlanetVars", new[] { "CampaignID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignPlanets", new[] { "CampaignID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "CampaignPlanets", new[] { "MissionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CampaignVars", new[] { "CampaignID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Clans", new[] { "FactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Clans", new[] { "ForumThreadID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CommanderDecorationIcons", new[] { "DecorationUnlockID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CommanderDecorations", new[] { "SlotID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "CommanderDecorations", new[] { "CommanderID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "CommanderDecorations", new[] { "DecorationUnlockID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CommanderModules", new[] { "SlotID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "CommanderModules", new[] { "CommanderID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "CommanderModules", new[] { "ModuleUnlockID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "CommanderSlots", new[] { "ChassisID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Commanders", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Commanders", new[] { "ChassisUnlockID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ContributionJars", new[] { "GuarantorAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Contributions", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Contributions", new[] { "ManuallyAddedAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Contributions", new[] { "ContributionJarID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "EventAccount", new[] { "AccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventAccount", new[] { "EventID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventClan", new[] { "ClanID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventClan", new[] { "EventID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventFaction", new[] { "EventID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventFaction", new[] { "FactionID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventPlanet", new[] { "EventID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventPlanet", new[] { "PlanetID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventSpringBattle", new[] { "EventID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "EventSpringBattle", new[] { "SpringBattleID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "FactionTreaties", new[] { "AcceptedAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "FactionTreaties", new[] { "ProposingAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "FactionTreaties", new[] { "AcceptingFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "FactionTreaties", new[] { "ProposingFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumCategories", new[] { "ParentForumCategoryID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumLastReads", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumLastReads", new[] { "ForumCategoryID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumPostEdits", new[] { "EditorAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumPostEdits", new[] { "ForumPostID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ForumPostWords", new[] { "ForumPostID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ForumPostWords", new[] { "WordID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ForumPosts", new[] { "AuthorAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumPosts", new[] { "ForumThreadID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ForumThreadLastReads", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumThreadLastReads", new[] { "ForumThreadID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ForumThreads", new[] { "CreatedAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumThreads", new[] { "LastPostAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "ForumThreads", new[] { "RestrictedClanID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ForumThreads", new[] { "ForumCategoryID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Galaxies", new[] { "WinnerFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "GameModes", new[] { "MaintainerAccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "GameModes", new[] { "ForumThreadID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "KudosPurchases", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "KudosPurchases", new[] { "UnlockID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Links", new[] { "GalaxyID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Links", new[] { "PlanetID1" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Links", new[] { "PlanetID2" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "LobbyNews", new[] { "AuthorAccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "MapPollOptions", new[] { "MapPollID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "MapPollOptions", new[] { "ResourceID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "MapRatings", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "MapRatings", new[] { "ResourceID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "MissionScores", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "MissionScores", new[] { "MissionID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Missions", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Missions", new[] { "ForumThreadID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "News", new[] { "AuthorAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "News", new[] { "ForumThreadID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PlanetFactions", new[] { "FactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PlanetFactions", new[] { "PlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PlanetOwnerHistories", new[] { "OwnerAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PlanetOwnerHistories", new[] { "OwnerClanID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PlanetOwnerHistories", new[] { "OwnerFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PlanetOwnerHistories", new[] { "PlanetID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "PlanetStructures", new[] { "OwnerAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PlanetStructures", new[] { "PlanetID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "PlanetStructures", new[] { "TargetPlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PlanetStructures", new[] { "StructureTypeID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Planets", new[] { "OwnerAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Planets", new[] { "OwnerFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Planets", new[] { "ForumThreadID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Planets", new[] { "GalaxyID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Planets", new[] { "MapResourceID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PollOptions", new[] { "PollID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "PollVotes", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PollVotes", new[] { "OptionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "PollVotes", new[] { "PollID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Polls", new[] { "CreatedAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Polls", new[] { "RoleTargetAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Polls", new[] { "RestrictClanID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Polls", new[] { "RestrictFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Polls", new[] { "RoleTypeID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Punishments", new[] { "AccountID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Punishments", new[] { "CreatedAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Ratings", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Ratings", new[] { "MissionID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ResourceContentFiles", new[] { "ResourceID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "ResourceDependencies", new[] { "ResourceID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "Resources", new[] { "TaggedByAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Resources", new[] { "ForumThreadID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Resources", new[] { "MissionID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "RoleTypeHierarchies", new[] { "MasterRoleTypeID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "RoleTypeHierarchies", new[] { "SlaveRoleTypeID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "RoleTypes", new[] { "RestrictFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "SpringBattleBots", new[] { "SpringBattleID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "SpringBattlePlayers", new[] { "AccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "SpringBattlePlayers", new[] { "SpringBattleID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "SpringBattles", new[] { "HostAccountID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "SpringBattles", new[] { "ForumThreadID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "SpringBattles", new[] { "MapResourceID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "SpringBattles", new[] { "ModResourceID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "StructureTypes", new[] { "EffectUnlockID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "TreatyEffects", new[] { "FactionTreatyID" }, DeleteBehavior.Cascade);
            Fk(modelBuilder, "TreatyEffects", new[] { "GivingFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "TreatyEffects", new[] { "ReceivingFactionID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "TreatyEffects", new[] { "PlanetID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "TreatyEffects", new[] { "EffectTypeID" }, DeleteBehavior.Restrict);
            Fk(modelBuilder, "Unlocks", new[] { "RequiredUnlockID" }, DeleteBehavior.Restrict);
        }

        /// <summary>
        /// Applies a facet by table and column name, skipping quietly if the model has no
        /// such property. Names are the database's, which is what the snapshot records;
        /// where a model property does not match, that is a difference the schema diff
        /// will report rather than something to crash on here.
        /// </summary>
        /// <summary>
        /// Sets a foreign key's delete behaviour, matched by the columns it is on. Skips
        /// quietly when the model has no such relationship - that is a difference the
        /// schema diff reports, not something to crash on here.
        /// </summary>
        private static void Fk(ModelBuilder modelBuilder, string table, string[] columns, DeleteBehavior behavior)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                foreach (var foreignKey in entity.GetForeignKeys())
                {
                    var names = foreignKey.Properties.Select(p => p.Name).ToArray();
                    if (names.Length != columns.Length) continue;
                    if (names.Except(columns).Any()) continue;
                    foreignKey.DeleteBehavior = behavior;
                    return;
                }
            }
        }

        /// <summary>Declares an index by table and column names, skipping if the model lacks them.</summary>
        private static void Index(ModelBuilder modelBuilder, string table, string[] columns, bool unique, string filter)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                // join tables are shared-type entities over Dictionary<string, object>;
                // modelBuilder.Entity() cannot take them
                if (entity.HasSharedClrType) continue;
                foreach (var column in columns)
                    if (entity.FindProperty(column) == null) return;
                var index = modelBuilder.Entity(entity.ClrType).HasIndex(columns);
                if (unique) index.IsUnique();

                // EF Core adds "WHERE [col] IS NOT NULL" to a unique index over a nullable
                // column. Sometimes the database agrees and sometimes it does not - SteamID
                // is filtered, Text and ShortName are not - so the filter is taken from the
                // schema per index rather than applied or removed by rule. A first attempt
                // removed them all and broke the one that was right.
                index.HasFilter(filter);
                return;
            }
        }

        private static void Facet(ModelBuilder modelBuilder, string table, string column,
            System.Action<Microsoft.EntityFrameworkCore.Metadata.Builders.PropertyBuilder> configure)
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                if (entity.GetTableName() != table) continue;
                // join tables are shared-type entities over Dictionary<string, object>;
                // modelBuilder.Entity() cannot take them
                if (entity.HasSharedClrType) continue;
                var property = entity.FindProperty(column);
                if (property == null) continue;
                configure(modelBuilder.Entity(entity.ClrType).Property(column));
                return;
            }
        }
    }
}
