#!/usr/bin/env python3
"""One map's metadata, in the exact form the website publishes it.

The lobby server reads map metadata from {ResourceBaseUrl}/{name}.metadata.xml.gz, which is
gzipped XmlSerializer output of ZkData.UnitSyncLib.Map. tools/stack.sh serves one of these from
the site container so the lobby server in the OTHER container has something real to fetch.

Written here rather than generated by the .NET serializer because nothing in the stack builds a
project that has it, and adding one to produce a test fixture is a lot of machinery for a file
this small. The shape is not guessed: it was taken from
MetaDataCache.SerializeAndCompressMetaData running under mono against a real Map.

It is self-checking anyway. If this XML stopped matching what XmlSerializer expects, the stack's
own !listmapoptions check would fail - the server would answer "this map has no map options",
which is exactly the failure the check exists to catch.
"""
import gzip
import sys

XML = '''<?xml version="1.0"?>
<Map xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>{name}</Name>
  <Dependencies />
  <Description>metadata served by tools/stack.sh</Description>
  <CheckSum>0</CheckSum>
  <ModType>0</ModType>
  <ExtractorRadius>0</ExtractorRadius>
  <Gravity>0</Gravity>
  <MaxMetal>0</MaxMetal>
  <MaxWind>0</MaxWind>
  <MinWind>0</MinWind>
  <Options>
    <Option>
      <Key>{option}</Key>
      <ListOptions />
      <Max>-3.40282347E+38</Max>
      <Min>-3.40282347E+38</Min>
      <Name>Stack Probe Option</Name>
      <Step>0</Step>
      <StrMaxLen>65535</StrMaxLen>
      <Type>Bool</Type>
    </Option>
  </Options>
  <Size>
    <Width>0</Width>
    <Height>0</Height>
  </Size>
  <TidalStrength>0</TidalStrength>
</Map>'''


def main():
    if len(sys.argv) != 4:
        print("usage: make-map-metadata.py <map-internal-name> <option-key> <output-file>", file=sys.stderr)
        return 2
    name, option, out = sys.argv[1], sys.argv[2], sys.argv[3]
    with gzip.open(out, "wb") as handle:
        handle.write(XML.format(name=name, option=option).encode("utf-8"))
    print("wrote %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
